config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"
  resources :books do
    resources :introduces
    resources :acts 
    collection do
      get 'category'
    end
    collection do 
      get 'search'
    end
  end
  
  resources :users, only: :show do
    collection do
      get "book"
    end
  end

  resources :conducts, only: :index
end

app/models/introduce.rb
class Introduce < ApplicationRecord
  belongs_to :user
  belongs_to :book

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :star

  # validates
  title_length = { maximum: 40, message: 'は40文字以内で記入してください' }
  content_length = { maximum: 1000, message: 'は1000文字以内で記入してください' }
  with_options presence: true do
    validates :title, length: title_length 
    validates :content, length: content_length
    validates :star_id
  end
end

app/controllers/introduces_controller.rb
class IntroducesController < ApplicationController
  before_action :move_to_log_in
  before_action :find_book,         except: :move_to_log_in
  before_action :find_introduce,    only: [:edit, :update, :destroy]
  before_action :categories
  before_action :confirm_introduce, only: [:new, :create, :edit, :update]
  before_action :rate,              only: [:new, :show, :edit]
  before_action :confirm_act,       only: [:new, :show, :create, :edit, :update]

  def new
    @introduce = Introduce.new
  end

  def create
    @introduce = Introduce.new(introduce_params)
    if @introduce.save
      redirect_to book_path(@introduce.book_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @introduce.update(introduce_params)
      redirect_to book_path(@book)
    else
      @exist = true
      render :edit
    end
  end

  def destroy
    @introduce.destroy
    redirect_to book_path(@book)
  end
  
  private
  def introduce_params
    params.require(:introduce).permit(:title, :content, :star_id).merge(user_id: current_user.id, book_id: params[:book_id])
  end
  
  def find_book
    @book = Book.find(params[:book_id])
  end
  
  def find_introduce
    @introduce = Introduce.find(params[:id])
  end
  
  def categories
    @categories = Category.all
  end
  
  # すでに紹介文があるか確認
  def confirm_introduce
    @exist = IntroduceConfirm.introduce(@book, current_user)
  end
  
  def move_to_log_in
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  # 評価
  def rate
    @rate = StarRate.rate(@book)
  end
    
  def confirm_act
    @acts = Act.where(book_id: @book.id, user_id: user.id )
    if @acts.present?
      @existAct = true
    end
  end
end

app/helpers/introduces_helper.rb
module IntroducesHelper
end

app/views/introduces/edit.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer">
    <div class="book-show main distinction">
      <%# 基本情報 %>
        <%= render partial: "shared/book_info", locals: {book: @book, rate: @rate,  existAct: @existAct, exist: @exist} %>
      <%# /基本情報 %>

      <div class="introduce-main-form view-right-side split">
        <div class="introduce-main-title">  
          Introduce
        </div>
        <%= form_with model: @introduce, url: book_introduce_path(@book, @introduce), method: :patch, local: true, class: "form-act" do |f|%>
          <%= render partial: 'shared/error_messages', locals: { model: @introduce } %>
          <div class="introduce-form-box">
            <div class="introduce-guide">
              タイトル
            </div>
            <div class="introduce-form">
              <%= f.text_field :title, class: "introduce-text-field", value: @introduce.title %>
            </div>
          </div>
          
          <div class="introduce-form-box">
            <div class="introduce-guide">
              紹介文
            </div>
            <div class="introduce-form">
              <%= f.text_area :content, class: "introduce-text-area", value: @introduce.content %>
            </div>
          </div>
          
          <div class="introduce-form-box recommend-star">
            <div class="introduce-guide">
              おすすめ度:
            </div>
            <div class="introduce-form">
              <%= f.collection_select(:star_id, Star.all, :id, :name, {include_blank: "---"}) %>
            </div>
          </div>

          <div class="introduce-submit">
            <%= f.submit "変更" %>
          </div>
        <% end %>
        <div class="back-to-show">
          <%= link_to "戻る", book_path(@book) %>
        </div>
      </div>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>

app/views/introduces/new.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>
  
  <div class="main-footer">
    <div class="book-show main distinction">
      <%# 基本情報 %>
      <%= render partial: "shared/book_info", locals: {book: @book, rate: @rate,  existAct: @existAct, exist: @exist} %>    
      <%# /基本情報 %>

      <div class="introduce-main-form view-right-side split">

        <div class="introduce-main-title">  
          Introduce
        </div>
        <%= form_with model: @introduce, url: book_introduces_path, local: true, class: "form-act" do |f|%>
          <%= render partial: 'shared/error_messages', locals: { model: f.object } %>
          <div class="introduce-form-box">
            <div class="introduce-guide">
              タイトル
            </div>
            <div class="introduce-form">
              <%= f.text_field :title, class: "introduce-text-field", value: @introduce.title %>
            </div>
          </div>
          
          <div class="introduce-form-box">
            <div class="introduce-guide">
              紹介文
            </div>
            <div class="introduce-form">
              <%= f.text_area :content, class: "introduce-text-area", value: @introduce.content %>
            </div>
          </div>
          
          <div class="introduce-form-box">
            <div class="introduce-guide">
              おすすめ度
            </div>
            <div class="introduce-form">
              <%= f.collection_select(:star_id, Star.all, :id, :name, {include_blank: "---"}) %>
            </div>
          </div>

          <div class="introduce-submit">
            <%= f.submit "登録" %>
          </div>
        <% end %>
        <div class="back-to-show">
          <%= link_to "戻る", book_path(@book) %>
        </div>
      </div>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>