config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"
  resources :books do
    resources :introduces
    resources :acts 
    collection do
      get 'category'
    end
    collection do 
      get 'search'
    end
  end
  
  resources :users, only: :show do
    collection do
      get "book"
    end
  end

  resources :conducts, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,       dependent: :destroy
  has_many :introduces,  dependent: :destroy
  has_many :acts,        dependent: :destroy

  # validate
  name_length = { maximum: 40 , message: "は40字以内で入れてください"}
  name = { with: /\A[a-zA-Z0-9]+\Z/, message: "は全角・スペース・記号を入れないでください" }
  email = { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "には'@'をつけてください" } 
  pass = { with: /(?=.*\d+.*)(?=.*[a-zA-Z]+.*)+/, message: 'は半角英数字を混合させて入力してください' }
  with_options presence: true do
    validates :name,  length: name_length, format: name
    validates :email, uniqueness: true, format: email
    validates :password, format: pass
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_books_category
  
  def show
    @introduces = @user.introduces
    @acts = @user.acts
    @num = 0 #viewで3つ目を数えるためのもの(book)
    @actNum = 0 #同上(act)
    @booksData = 0
    @actsData = 0

    @introduces.each do |introduce|
      @booksData += 1
    end

    @acts.each do |act|
      @actsData+= 1
    end
  end
  
  def book
  end
  
  private
  def find_books_category
    @categories = Category.all
    @books = Book.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/book.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>
  
  <%# header下線 %>
  <div class="header-border">
  </div>
  <%# /header下線 %>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer">
    <div class="main book-main">
      <div class="book-introduce-list">
        <%# 本の紹介リスト %>
        <%= render partial: "shared/books", locals: {books: @books} %>
      </div>
      <%# 本の紹介リスト %>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>
  
  <%# header下線 %>
  <div class="header-border">
  </div>
  <%# /header下線 %>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer user-show-main">
    <div class="main book-main">

      <div class="book-introduce-list">
        <%# 本の紹介リスト %>
        <div class="book-introduce-title">
          <span>紹介文記入済み本</span>
        </div>
        <div class="book-index user-show-index">
          <% if @books.present? %>
            <ul>
              <%# 本の紹介文を一つずつ出していき、ログインユーザーが紹介文を書いてれば@numに1を加算。@numが３以上になったところで繰り返し終了 %>
              <% @books.each do |book| %>
                <% book.introduces.each do |introduce| %>
                  <% if introduce.user == @user %>
                    <%= link_to book_path(book) do %>
                      <li>
                        <div class="root-book-img">
                          <% if book.image.attached? %>
                            <%= image_tag book.image.variant(resize: '300x300') %>
                          <% else %>
                            <div class="no-image">
                              No Image
                            </div>
                          <% end %>
                          <span class="category-name"><%= book.category.name %></span>
                        </div>
                        <div class="root-book-title">
                          <span><%= book.title %></span>
                        </div>
                        <div clas="root-book-writer">
                          著者：
                          <span><%= book.writer %></span>
                        </div>
                      </li>
                      <%# @numが3以上で抜ける %>
                      <% break if @num == 3 %>
                    <% end %>
                    <% @num += 1 %>
                  <% end %>
                <% end %>
              <% end %>
            </ul>
          <% else %>
            <span>登録されている本がありません</span>
          <% end %>
        </div>
        <%# 紹介文の数により表示変化 %>
        <% if @num == 0 %>
          <div class="user-none-introduce">
            <span>登録されている本がありません</span>
          </div>
        <% elsif @booksData > 3 %>
          <div class="introduce-more book-more">
            <%= link_to "もっと見る", book_users_path %>
          </div>
        <% end %>

        <div class="book-border-bottom">
      </div>
      <%# 本の紹介リスト %>

      <%# 紹介文リスト %>
      <div class="act-index show-user-act-index">
        <% if @acts.present? %>
          <div class="act-big-title user-show-act-title">
            <div class="title-side">
              <span>Title<span>
            </div>
            <div class="sentence-side">
              <span>Sentence</span>
            </div>
          </div>
          <div class="introduce-down-side">
            <% current_user.acts.each do |act| %>
              <div class="act-table-list user-show-act-list">
                <div class="act-index-content title-content-side">
                  <%= link_to book_path(act.book) do %>
                    <div class="act-table-th">
                      <span><%= act.book.title %></span>
                    </div>
                  <% end %>
                </div>
                <div class="act-index-content sentence-content-side">
                  <div class="act-index-content">
                    <%= link_to book_acts_path(act.book) do %>
                      <div class="act-table-td">
                        <span><%= act.content %></span>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <% @actNum += 1 %>
              <% break if @actNum == 3 %>
            <% end %>
          </div>
        <% else %>
          <div class="act-none">
            <span>登録されているActがありません</span>
          </div>
        <% end %>
        <%# 紹介文の数により表示変化 %>
        <% if @actsData > 3 %>
          <div class="introduce-more act-more">
            <%= link_to "もっと見る", conducts_path %>
          </div>
        <% end %>
      </div>
    </div>


    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>