config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"
  resources :books do
    resources :introduces
    resources :acts 
    collection do
      get 'category'
    end
    collection do 
      get 'search'
    end
  end
  
  resources :users, only: :show do
    collection do
      get "book"
    end
  end

  resources :conducts, only: :index
end

app/views/shared/_acts_show.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer">
    <div class="book-show main distinction">
      <%# 基本情報 %>
      <%= render partial: "shared/book_info", locals: {book: book, rate: rate,  existAct: existAct, exist: exist} %>
      <%# /基本情報 %>

      <%# 紹介文 %>
      <% if @acts.present? %>
        <div class="acts-contents view-right-side split">  
          <% @acts.each do |act| %>
            <div class="act-l-box">
              <%# ワード %>
              <div class="act-content">
                <div class="act-guide">
                  <span>Sentence</span>
                </div>
                <div class="content-box">
                  <%= act.content %>
                  (<%= act.page %>ページ)
                </div>
              </div>
              <%# /ワード %>

              <%# ポイント %>
              <div class="act-content">
                <div class="act-guide">
                  <span>Point</span>
                </div>
                <div class="content-box">
                  <%= act.point %>
                </div>
              </div>
              <%# /ポイント %>

              <%# Act %>
              <div class="act-content">
                <div class="act-guide">
                  <span>Act</span>
                </div>
                <div class="content-box">
                  <%= act.act %>
                </div>
              </div>
              <%# /Act %>

              <%# act-option %>
              <div class="act-index-options">
                <div class="tp-act-edit">
                  <%= link_to "編集", edit_book_act_path(act.book, act) %>
                </div>
                <div class="tp-act-destroy">
                  <%= link_to "削除", book_act_path(act.book, act), method: :delete %>
                </div>
              </div>
              <%# /act-option %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>

app/views/shared/_book_info.html.erb
<div class="book-show-upper split">
  <div class="notifications">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: key) %>
    <% end %>
  </div>
  <div class="upper-left">
    <div class="show-book-img">
      <%= link_to book_path(book) do %>
        <% if book.image.attached? %>
          <div class="info-image">
            <span class="info-category-name"><%= book.category.name %></span>
            <%= image_tag book.image.variant(resize: '300x300') %>
          </div>
        <% else %>
          <div class="info-no-image">
            <span class="info-category-name-none-image"><%= book.category.name %></span>
          </div>
          <div class="none-image-text">
            No Image
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <%# 星評価 %>
  <div class="star-box">
    <% if rate.present? %>
      <div class="stars" data-rate="<%= rate %>">
      </div>
    <% end %>
  </div>
  <%# /星評価 %>

  <div class="upper-right">
    <div class="show-book-title">
      <dl>
        <dt>
          タイトル
        </dt>
        <dd>
          <span><%= book.title %></span>
        </dd>
      </dl>
    </div>
    <div clas="show-book-writer">
      <dl>
        <dt>
          著者
        </dt>
        <dd>
          <span><%= book.writer %></span>
        </dd>
      </dl>
    </div>
    <div class="publish">
      <dl>
        <dt>
          発行会社
        </dt>
        <dd>
          <span><%= book.publish.strftime('%Y/%m/%d') %></span>
        </dd>
      </dl>
    </div>

    <div class="info-link-to">
      <% if existAct == true %>
        <div class="link-to-act-index info-link">
          <%= link_to "この本のAct一覧", book_acts_path(book) %>
        </div>
      <% end %>

      <div class="new-act-link info-link">
        <%= link_to "Actを作成する", new_book_act_path(@book, @act)%>
      </div>

      <% if exist != true %>
        <div class="link-to-new-introduce info-link">
          <%= link_to "紹介文を作成する", new_book_introduce_path(book) %>
        </div>
      <% else %>
        <div class="link-to-new-introduce info-link">
          <%= link_to "紹介文", book_path(book) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_books.html.erb
<div class="book-index">
  <% if books.present? %>
    <ul>
      <% books.each do |book| %>
        <%= link_to book_path(book) do %>
          <li>
            <div class="root-book-img">
              <% if book.image.attached? %>
                <%= image_tag book.image.variant(resize: '300x300') %>
              <% else %>
                <div class="no-image">
                  No Image
                </div>
              <% end %>
              <span class="category-name"><%= book.category.name %></span>
            </div>
            <div class="root-book-title list-text">
              <span><%= book.title %></span>
            </div>
            <div class="root-book-writer list-text">
              著者：
              <span><%= book.writer %></span>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <span>登録されている本がありません</span>
  <% end %>
</div>

app/views/shared/_category_list.html.erb
<div class="category-lists">
  <ul class="hidden-category-list">
    <% categories.each do |category| %>
      <li class="category-list">
        <%= link_to category.name, category_books_path(category_id: category.id), class:"category-link" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_devise_footer.html.erb
<div class="footer-app-title">
  <%= link_to "BookAct", root_path %>
</div>
<ul>
  <li>
    <%= link_to "本一覧", books_path %>
  </li>
  <li>
    <%= render "devise/shared/links" %>
  </li>
</ul>

app/views/shared/_devise_header.html.erb
<div class="app-title">
  <%= link_to "BookAct", root_path %>
</div>
<ul>
  <li>
    <%= link_to "本一覧", books_path %>
  </li>
  <li>
      <%= render "devise/shared/links" %>
  </li>
</ul>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert" >
  <ul id="error-list">
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-app-title">
  <%= link_to "BookAct", root_path %>
</div>
<ul>
  <% if @user.present? %>
    <li>
      <%= link_to "本一覧", books_path %>
    </li>
    <li>
      <%= link_to "Act一覧", conducts_path %>
    </li>
    <li>
      <%= link_to "本の登録", new_book_path %>
    </li>
    <li>
      <%= link_to "#{@user.name}", user_path(@user) %>
    </li>
    <li>
        <%= link_to "log out", destroy_user_session_path, method: :delete %>
    </li>
  <% else %>
    <li>
      <%= link_to "本一覧", books_path %>
    </li>
    <li>
      <%= link_to "log in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "sign up", new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/shared/_header.html.erb
<div class="app-title">
  <%= link_to "BookAct", root_path %>
</div>
<ul>
  <% if @user.present? %>
    <li>
      <%= link_to "本一覧", books_path %>
    </li>
    <li>
      <%= link_to "本の登録", new_book_path, class: "link-to-new-book" %>
    </li>
    <li class="header-category category-range">
      <a href="#">
        カテゴリー
        <div class="arrow"></div>
      </a>
    </li>
    <li class="to-act-index">
      <%= link_to "Act一覧", conducts_path %>
    </li>
    <li class="mypage">
      <%= link_to "#{@user.name}", user_path(@user) %>
    </li>
  <% else %>
    <li>
      <%= link_to "本一覧", books_path %>
    </li>
    <li>
      <%= link_to 'log in', new_user_session_path %>
    </li>
    <li>
      <%= link_to "sign up", new_user_registration_path %>
    </li>
  <% end %>
  <li>
    <%= render "shared/search" %>
  </li>
</ul>

app/views/shared/_search.html.erb
    <%= form_with url: search_books_path, local: true, method: :get do |f| %>
      <div class="search-books-form">
        <div class="search-books-form-box">
          <%= f.text_field :keyword, placeholder: "タイトルから本を検索する", class: "search-books" %>
        </div>
        <div class="search-submit">
          <%= f.submit "検索", class: "submit" %>
        </div>
      </div>
    <% end %>

app/views/shared/footer.html.erb
<ul>
  <li>
    <%= link_to "本一覧", books_path %>
  </li>
  <li>
    <%#= link_to "カテゴリー", %>
    カテゴリー
  </li>
  <li>
    <%#= link_to "my　page", %>
    my　page
  </li>
</ul>