config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"
  resources :books do
    resources :introduces
    resources :acts 
    collection do
      get 'category'
    end
    collection do 
      get 'search'
    end
  end
  
  resources :users, only: :show do
    collection do
      get "book"
    end
  end

  resources :conducts, only: :index
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to       :user
  has_many         :introduces, dependent: :destroy
  has_one_attached :image
  has_many         :acts, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  # validates
  title_length = { maximum: 40, message: 'は40文字以内で記入してください' }
  writer_length = { maximum: 100, message: 'は100文字以内で記入してください' }
  with_options presence: true do
    validates :category_id
    validates :title,  length: title_length
    validates :writer, length: writer_length
    validates :publish
    validates :company, length: title_length
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book,         except: [:index, :create, :book_params, :rate]
  before_action :move_to_devise,    except: :index
  before_action :categories,        only: [:index, :new, :edit, :show, :create, :category, :search]
  before_action :confirm_introduce, only: [:edit, :show]
  before_action :rate,              only: [:show, :edit]
  before_action :confirm_act,       only: [:edit, :update, :show]
  require 'date'

  def index
    @books = Book.all.includes(:user)
    @categories = Category.all
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    Book.all.each do |b|
      if (b.title == @book.title) && (b.writer == @book.writer) 
        flash[:notice] = 'すでに登録されています'
        return redirect_to new_book_introduce_path(@book, book_id: b.id)
      end
    end
    if @book.save
      redirect_to new_book_introduce_path(@book)
    else
      render :new
    end
  end
  
  def show
    @introduces = @book.introduces
  end
  
  def edit
  end
  
  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  def destroy
  end
  
  def category
    @data = params[:category_id]
    @category = Category.find_by(id: @data)
    @books = Book.where(category_id: @data)
  end
  
  def search
    @books = SearchBooks.search(params[:keyword])
  end
  
  private
  def book_params
    params.permit(:title, :writer, :company, :content, :publish, :category_id, :image).merge(user_id: current_user.id)
  end
  
  def move_to_devise
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
  
  def find_book
    @book = Book.find_by(id: params[:id])
  end
  
  def categories
    @categories = Category.all
  end
  
  # すでに紹介文があるか確認
  def confirm_introduce
    @exist = IntroduceConfirm.introduce(@book, current_user)
  end
  
  # 評価
  def rate
    @rate = StarRate.rate(@book)
  end

  def confirm_act
    @acts = Act.where(book_id: @book.id, user_id: user.id )
    if @acts.present?
      @existAct = true
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/category.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>  
  </div >
  
  <%# header下線 %>
  <div class="header-border">
  </div>
  <%# /header下線 %>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>
  
  <div class="main-footer">
    <div class="main category-main">
      <div class="category-indiv-name">
        <%= @category.name%>
      </div>
        <%= render partial: "shared/books", locals: {books: @books} %>    
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer">
    <div class="main distinction">
      <%# 基本情報 %>
      <%= render partial: "shared/book_info", locals: {book: @book, rate: @rate,  existAct: @existAct, exist: @exist} %>
      <%# /基本情報 %>
      <div class="main book-form-main view-right-side split">
        <%= form_with  url: books_path, method: :patch, local: true do |f| %>
          <%= render partial: 'shared/error_messages', locals: { model: f.object } %>
          <div class="book-form-contens">
          
            <div class="book-form-box">
              <div class="book-form-guide">
                本のタイトル
              </div>
              <div class="book-form">
                <%= f.text_field :title, class: "new-book-form", value: "#{@book.title}" %>
              </div>
            </div>
          
            <div class="book-form-box">
              <div class="book-form-guide">
                著者
              </div>
              <div class="book-form">
                <%= f.text_field :writer, class: "new-book-form", value: "#{@book.writer}" %>
              </div>
            </div>
        
            <div class="book-form-box">
              <div class="book-form-guide">
                出版社
              </div>
              <div class="book-form">
                <%= f.text_field :company, class: "new-book-form", value: "#{@book.company}" %>
              </div>
            </div>  
        
            <div class="book-form-box">
              <div class="book-form-guide">
                発行日
              </div>
              <div class="book-form">
                <%= f.date_select(
                  :publish,
                  use_month_numbers: true,
                  end_year: (Time.now.year),
                  default: Date.new(1980,1,1),
                  date_separator: '/'
                  ) 
                %>
              </div>
            </div>  

            <div class="book-form-box">
              <div class="book-form-guide">
                カテゴリー
              </div>
              <div class="book-form">
                <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: '---'} )%>
              </div>
            </div>

            <div class="book-form-box">
              <div class="book-form-guide">
                画像
              </div>
              <div class="book-form">
                <%= f.file_field :image, id:"item-image", class:"item-image" %>
              </div>
            </div>  

          </div>
            </div>  
            <%= f.submit "更新" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>
  
  <%# header下線 %>
  <div class="header-border">
  </div>
  <%# /header下線 %>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer">
    <div class="main book-main">

      <div class="catch-flase">
        <div class="top-video">
          <video autoplay muted playsinline src="/videos/book.mp4"></video>
        </div>
        <div class="video-flase">
          <span>今日、何を読む？</span>
        </div>
      </div>
        <%# 検索機能 %>

      <div class="book-introduce-list">

        <%# 本の紹介リスト %>
        <%= render partial: "shared/books", locals: {books: @books} %>
      </div>
      <%# 本の紹介リスト %>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>
   
  <%# header下線 %>
  <div class="header-border">
  </div>
  <%# /header下線 %>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer">
    <div class="main book-form-main">
      <div class="new-book-title">
        <span>本の登録</span>
      </div>
      <%= form_with url: books_path, method: :post, local: true, class: " book-new-form-main" do |f| %>
        <%= render partial: 'shared/error_messages', locals: { model: @book } %>
        <div class="book-form-contens">

        
          <div class="book-form-box book-new-form-box">
            <div class="book-form-guide book-new-guide">
              本のタイトル
            </div>
            <div class="book-form book-new-form">
              <%= f.text_field :title, class: "new-book-form", value: "#{@book.title}" %>
            </div>
          </div>
        
          <div class="book-form-box book-new-form-box">
            <div class="book-form-guidee book-new-guide">
              著者
            </div>
            <div class="book-form book-new-form">
              <%= f.text_field :writer, class: "new-book-form", value: "#{@book.writer}" %>
            </div>
          </div>
      
          <div class="book-form-box book-new-form-box">
            <div class="book-form-guidee book-new-guide">
              出版社
            </div>
            <div class="book-form book-new-form">
              <%= f.text_field :company, class: "new-book-form", value: "#{@book.company}" %>
            </div>
          </div>  
      
          <div class="book-form-box book-new-form-box">
            <div class="book-form-guidee book-new-guide">
              発行日
            </div>
            <div class="book-form book-new-form">
              <%= f.date_select(
                :publish,
                use_month_numbers: true,
                end_year: (Time.now.year),
                default: Date.new(1980,1,1),
                date_separator: '/'
                ) 
              %>
            </div>
          </div>  

          <div class="book-form-box book-new-form-box">
            <div class="book-form-guidee book-new-guide">
              カテゴリー
            </div>
            <div class="book-form book-new-form">
              <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: '---'})%>
            </div>
          </div>

          <div class="book-form-box book-new-form-box">
            <div class="book-form-guidee book-new-guide">
              画像
            </div>
            <div class="book-form book-new-form">
              <%= f.file_field :image, id:"item-image", class:"item-image" %>
            </div>
          </div>  
          
          <div class="book-new-submit">
            <%= f.submit "登録", class: "make-book-submit" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>

app/views/books/search.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>
  
  <%# header下線 %>
  <div class="header-border">
  </div>
  <%# /header下線 %>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer">
    <div class="main book-main">
        <%# 検索機能 %>

      <div class="book-introduce-list">
        <%# 追加リンク %>

        <%# 本の紹介リスト %>
        <%= render partial: "shared/books", locals: {books: @books} %>
      </div>
      <%# 本の紹介リスト %>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="l-body">  
  <div class="header">
    <%= render "shared/header" %>
  </div>

  <%# 開閉メニュー %>
  <%= render partial: "shared/category_list", locals: {categories: @categories} %>
  <%# /開閉メニュー %>

  <div class="main-footer">
    <div class="book-show main distinction">
      <%# 基本情報 %>
      <%= render partial: "shared/book_info", locals: {book: @book, rate: @rate,  existAct: @existAct, exist: @exist} %>
      <%# /基本情報 %>

      <%# 紹介文 %>
      <% if @introduces.present? %>
        <div class="book-introduce view-right-side split">  
          <% @introduces.each do |introduce| %>
            <div class="introduce-body">
              <div class="introduce-top">
                <div class="introduce-title">
                  <%= introduce.title %>
                </div>
              </div>
              <div class="introduce-content">
                <%= simple_format(introduce.content) %>
              </div>

              <div class="introduce-options">
                <% if introduce.user == current_user %>
                  <div class="introduce-edit">
                    <%= link_to "編集", edit_book_introduce_path(@book, introduce) %>
                  </div>
                  <div class="introduce-destroy">
                    <%= link_to "削除", book_introduce_path(@book, introduce), method: :delete %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="book-introduce view-right-side none-contents">  
          <span>登録されている紹介がありません</span>
        </div>
      <% end %>
    </div>

    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </div>
</div>